namespace Engine.Input;


public static class InputKeyMap {

    public static Keys FromKey (Silk.NET.Input.Key key) => key switch {
        Silk.NET.Input.Key.A => Keys.A,
        Silk.NET.Input.Key.B => Keys.B,
        Silk.NET.Input.Key.C => Keys.C,
        Silk.NET.Input.Key.D => Keys.D,
        Silk.NET.Input.Key.E => Keys.E,
        Silk.NET.Input.Key.F => Keys.F,
        Silk.NET.Input.Key.G => Keys.G,
        Silk.NET.Input.Key.H => Keys.H,
        Silk.NET.Input.Key.I => Keys.I,
        Silk.NET.Input.Key.J => Keys.J,
        Silk.NET.Input.Key.K => Keys.K,
        Silk.NET.Input.Key.L => Keys.L,
        Silk.NET.Input.Key.M => Keys.M,
        Silk.NET.Input.Key.N => Keys.N,
        Silk.NET.Input.Key.O => Keys.O,
        Silk.NET.Input.Key.P => Keys.P,
        Silk.NET.Input.Key.Q => Keys.Q,
        Silk.NET.Input.Key.R => Keys.R,
        Silk.NET.Input.Key.S => Keys.S,
        Silk.NET.Input.Key.T => Keys.T,
        Silk.NET.Input.Key.U => Keys.U,
        Silk.NET.Input.Key.V => Keys.V,
        Silk.NET.Input.Key.W => Keys.W,
        Silk.NET.Input.Key.X => Keys.X,
        Silk.NET.Input.Key.Y => Keys.Y,
        Silk.NET.Input.Key.Z => Keys.Z,

        Silk.NET.Input.Key.Number0 => Keys.Alpha0,
        Silk.NET.Input.Key.Number1 => Keys.Alpha1,
        Silk.NET.Input.Key.Number2 => Keys.Alpha2,
        Silk.NET.Input.Key.Number3 => Keys.Alpha3,
        Silk.NET.Input.Key.Number4 => Keys.Alpha4,
        Silk.NET.Input.Key.Number5 => Keys.Alpha5,
        Silk.NET.Input.Key.Number6 => Keys.Alpha6,
        Silk.NET.Input.Key.Number7 => Keys.Alpha7,
        Silk.NET.Input.Key.Number8 => Keys.Alpha8,
        Silk.NET.Input.Key.Number9 => Keys.Alpha9,

        Silk.NET.Input.Key.F1 => Keys.F1,
        Silk.NET.Input.Key.F2 => Keys.F2,
        Silk.NET.Input.Key.F3 => Keys.F3,
        Silk.NET.Input.Key.F4 => Keys.F4,
        Silk.NET.Input.Key.F5 => Keys.F5,
        Silk.NET.Input.Key.F6 => Keys.F6,
        Silk.NET.Input.Key.F7 => Keys.F7,
        Silk.NET.Input.Key.F8 => Keys.F8,
        Silk.NET.Input.Key.F9 => Keys.F9,
        Silk.NET.Input.Key.F10 => Keys.F10,
        Silk.NET.Input.Key.F11 => Keys.F11,
        Silk.NET.Input.Key.F12 => Keys.F12,

        Silk.NET.Input.Key.Escape => Keys.Escape,
        Silk.NET.Input.Key.Tab => Keys.Tab,
        Silk.NET.Input.Key.CapsLock => Keys.CapsLock,
        Silk.NET.Input.Key.ShiftLeft => Keys.LeftShift,
        Silk.NET.Input.Key.ShiftRight => Keys.RightShift,
        Silk.NET.Input.Key.ControlLeft => Keys.LeftControl,
        Silk.NET.Input.Key.ControlRight => Keys.RightControl,
        Silk.NET.Input.Key.AltLeft => Keys.LeftAlt,
        Silk.NET.Input.Key.AltRight => Keys.RightAlt,
        Silk.NET.Input.Key.Space => Keys.Space,
        Silk.NET.Input.Key.Enter => Keys.Enter,
        Silk.NET.Input.Key.Backspace => Keys.Backspace,
        Silk.NET.Input.Key.Delete => Keys.Delete,
        Silk.NET.Input.Key.Insert => Keys.Insert,
        Silk.NET.Input.Key.Home => Keys.Home,
        Silk.NET.Input.Key.End => Keys.End,
        Silk.NET.Input.Key.PageUp => Keys.PageUp,
        Silk.NET.Input.Key.PageDown => Keys.PageDown,

        Silk.NET.Input.Key.Up => Keys.Up,
        Silk.NET.Input.Key.Down => Keys.Down,
        Silk.NET.Input.Key.Left => Keys.Left,
        Silk.NET.Input.Key.Right => Keys.Right,

        Silk.NET.Input.Key.Keypad0 => Keys.Keypad0,
        Silk.NET.Input.Key.Keypad1 => Keys.Keypad1,
        Silk.NET.Input.Key.Keypad2 => Keys.Keypad2,
        Silk.NET.Input.Key.Keypad3 => Keys.Keypad3,
        Silk.NET.Input.Key.Keypad4 => Keys.Keypad4,
        Silk.NET.Input.Key.Keypad5 => Keys.Keypad5,
        Silk.NET.Input.Key.Keypad6 => Keys.Keypad6,
        Silk.NET.Input.Key.Keypad7 => Keys.Keypad7,
        Silk.NET.Input.Key.Keypad8 => Keys.Keypad8,
        Silk.NET.Input.Key.Keypad9 => Keys.Keypad9,
        Silk.NET.Input.Key.KeypadDecimal => Keys.KeypadPeriod,
        Silk.NET.Input.Key.KeypadDivide => Keys.KeypadDivide,
        Silk.NET.Input.Key.KeypadMultiply => Keys.KeypadMultiply,
        Silk.NET.Input.Key.KeypadSubtract => Keys.KeypadMinus,
        Silk.NET.Input.Key.KeypadAdd => Keys.KeypadPlus,
        Silk.NET.Input.Key.KeypadEnter => Keys.KeypadEnter,
        Silk.NET.Input.Key.KeypadEqual => Keys.KeypadEquals,

        Silk.NET.Input.Key.Comma => Keys.Comma,
        Silk.NET.Input.Key.Period => Keys.Period,
        Silk.NET.Input.Key.Slash => Keys.Slash,
        Silk.NET.Input.Key.Semicolon => Keys.Semicolon,
        Silk.NET.Input.Key.Apostrophe => Keys.Quote,
        Silk.NET.Input.Key.LeftBracket => Keys.LeftBracket,
        Silk.NET.Input.Key.RightBracket => Keys.RightBracket,
        Silk.NET.Input.Key.BackSlash => Keys.Backslash,
        Silk.NET.Input.Key.Minus => Keys.Minus,
        Silk.NET.Input.Key.Equal => Keys.Equals,
        Silk.NET.Input.Key.GraveAccent => Keys.BackQuote,

        Silk.NET.Input.Key.PrintScreen => Keys.Print,

        _ => Keys.None
    };

    public static Keys FromMouseButton (Silk.NET.Input.MouseButton button) => button switch {
        Silk.NET.Input.MouseButton.Left => Keys.Mouse0,
        Silk.NET.Input.MouseButton.Right => Keys.Mouse1,
        Silk.NET.Input.MouseButton.Middle => Keys.Mouse2,
        Silk.NET.Input.MouseButton.Button4 => Keys.Mouse3,
        Silk.NET.Input.MouseButton.Button5 => Keys.Mouse4,
        _ => Keys.None
    };

}